# version: '3.8'

services:
  db:
    image: mysql:8
    container_name: lawfirm_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lawfirm_db
      MYSQL_USER: lawfirm_user
      MYSQL_PASSWORD: secret123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lawfirm_app
    ports:
      - "8080:8080"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: lawfirm_user
      PMA_PASSWORD: secret123

volumes:
  db_data:
